### ISSUE TITLE
talkpage link text always "Start a Discussion"

### ISSUE THREAD

**Issue by nallison** [splitbrain/dokuwiki-plugin-talkpage#1]
Hi Andi,

Thanks for your plugin that I found via the forum: https://forum.dokuwiki.org/thread/8982.

I installed this on the most recent dokuwiki and the standard "dokuwiki" template.  I found the link in the sidebar said "Start a Discussion" even when the discussion page for a topic existed.  When I look at the code in syntax.php on line 57 I found variable $talkpage:
<code> 
// we want to the talk page
$goto = $talkns .':'.$INFO['id'];
if(page_exists($talkpage)){ 
</code>

I tried changing the variable to $goto (as defined in previous line) and found the link text changed between "Start a Discussion" and "Discuss the Page" correctly depending on if the talk: page existed: <code>
// we want to the talk page
$goto = $talkns .':'.$INFO['id'];
if(page_exists($goto)){
</code>

I am sorry if I misunderstand and have been the victim of a lucky series of unrelated coincidences?

Kind regards
Neil

**Comment by atlarep** [comment]
I know it's not relevant to the issue, but any idea of how I can have 'Discussion' pointed at a specific page?
I'd all discussions to happen in one page in my wiki. Is this possible?

**Comment by splitbrain** [comment]
has been fixed in e2c175c28a6b01c27c08945b163cc3004d93c702

**Comment by atlarep** [comment]
Thanks
