### ISSUE TITLE
automatic template on creation

### ISSUE THREAD

**Issue by dinobib** [splitbrain/dokuwiki-plugin-talkpage#6]
Hi,
Sorry, it’s not relaie an issue but more a question and maybe a feature request.
I use the talkpage plugin with a namespace template to automatically insert the discussion tag `~~DISCUSSION~~` from discussion plugin. 
I wish to modify the link creating the discussion in order to automaticcaly create the page and saving it in order to people to directly have the page with discussion without the page don’t exist and creating and saving page process.
I thought it must be possible with parameter in the creating link. Tell me if I am wrong ?
Would it be more difficult to provide such behaviour?

I was thinking that if we could do this, it would be great to have this option optable in the config manager as I think many people expect such beahaviour: click on creating discussion link and directly have a page with the disussion form (from discussion plugin).

Thanks for any idea, help, infos…

**Comment by splitbrain** [comment]
I don't think that's in the scope of this plugin. Maybe ask for this kind of feature in the discussion plugin itself.
